// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MidiKaval.Api.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MidiKaval.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615204455_AddCaseAssignments")]
    partial class AddCaseAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MidiKaval.Api.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("EventType", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_events_event_type_created_at_utc");

                    b.HasIndex("OrganisationId", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_events_organisation_id_created_at_utc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("MidiKaval.Api.Domain.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid?>("AssignedWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_worker_id");

                    b.Property<int?>("BeneficiaryAge")
                        .HasColumnType("integer")
                        .HasColumnName("beneficiary_age");

                    b.Property<string>("BeneficiaryContact")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("beneficiary_contact");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("beneficiary_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CrimeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("crime_number");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_stage");

                    b.Property<string>("Domicile")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("domicile");

                    b.Property<bool>("IsFirstTimeOffender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_first_time_offender");

                    b.Property<DateTime?>("NextVisitDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_visit_due_at_utc");

                    b.Property<string>("OffenceClassification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("offence_classification");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("StNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("st_number");

                    b.Property<string>("TypeOfOffence")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type_of_offence");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("VisitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("visit_count");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.HasIndex("AssignedWorkerId")
                        .HasDatabaseName("ix_cases_assigned_worker_id");

                    b.HasIndex("OrganisationId", "AssignedWorkerId")
                        .HasDatabaseName("ix_cases_organisation_id_assigned_worker_id");

                    b.HasIndex("OrganisationId", "CrimeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cases_organisation_id_crime_number");

                    b.HasIndex("OrganisationId", "StNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cases_organisation_id_st_number");

                    b.HasIndex("OrganisationId", "UpdatedAtUtc")
                        .HasDatabaseName("ix_cases_organisation_id_updated_at_utc");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("MidiKaval.Api.Domain.Entities.CaseAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("FromWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_worker_id");

                    b.Property<string>("NextVisitPurpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("next_visit_purpose");

                    b.Property<string>("OpenItems")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("open_items");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PriorActions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("prior_actions");

                    b.Property<Guid>("ToWorkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_worker_id");

                    b.HasKey("Id")
                        .HasName("pk_case_assignments");

                    b.HasIndex("OrganisationId", "CaseId")
                        .HasDatabaseName("ix_case_assignments_organisation_id_case_id");

                    b.HasIndex("OrganisationId", "ToWorkerId")
                        .HasDatabaseName("ix_case_assignments_organisation_id_to_worker_id");

                    b.ToTable("case_assignments", (string)null);
                });

            modelBuilder.Entity("MidiKaval.Api.Domain.Entities.CaseSearchPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_case_search_presets");

                    b.HasIndex("OrganisationId", "UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_case_search_presets_organisation_id_user_id_name");

                    b.ToTable("case_search_presets", (string)null);
                });

            modelBuilder.Entity("MidiKaval.Api.Domain.Entities.CaseStageTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("FromStage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("from_stage");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("ToStage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("to_stage");

                    b.HasKey("Id")
                        .HasName("pk_case_stages");

                    b.HasIndex("CaseId", "CreatedAtUtc")
                        .HasDatabaseName("ix_case_stages_case_id_created_at_utc");

                    b.ToTable("case_stages", (string)null);
                });

            modelBuilder.Entity("MidiKaval.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("token_version");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("OrganisationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_organisation_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MidiKaval.Api.Domain.Entities.Case", b =>
                {
                    b.HasOne("MidiKaval.Api.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cases_users_assigned_worker_id");
                });
#pragma warning restore 612, 618
        }
    }
}
