export const EVENT_TYPE_LABELS: Record<string, string> = {
  'auth.login.success': 'Login success',
  'auth.login.failed': 'Login failed',
  'auth.otp.failed': 'OTP failed',
  'auth.logout': 'Logout',
  'auth.refresh.success': 'Token refreshed',
  'auth.session.invalidated': 'Session invalidated',
  'auth.password_reset.requested': 'Password reset requested',
  'auth.password_reset.completed': 'Password reset completed',
  'auth.confirmation_token_created': 'Confirmation token created',
  'auth.account_created': 'Account created',
  'auth.email_confirmed': 'Email confirmed',
  'auth.confirmation_delivery_failed': 'Confirmation delivery failed',
  'auth.confirmation_delivered': 'Confirmation delivered',
  'case.created': 'Case created',
  'case.stage.changed': 'Case stage changed',
  'case.stage2_data.created': 'Stage 2 data created',
  'case.stage2_data.updated': 'Stage 2 data updated',
  'case.stage3_data.created': 'Stage 3 data created',
  'case.stage3_data.updated': 'Stage 3 data updated',
  'case.stage4_placement.created': 'Stage 4 placement created',
  'case.stage4_placement.updated': 'Stage 4 placement updated',
  'case.stage5_reintegration.created': 'Stage 5 reintegration created',
  'case.stage5_reintegration.updated': 'Stage 5 reintegration updated',
  'case.stage6_termination_exclusion.created': 'Stage 6 termination created',
  'case.stage6_termination_exclusion.updated': 'Stage 6 termination updated',
  'case.merged': 'Case merged',
  'case.transferred': 'Case transferred',
  'case.related.created': 'Case linked',
  'case.related.deleted': 'Case unlinked',
  'case.gps.verified': 'GPS verified',
  'case.pii.revealed': 'PII revealed',
  'case.note.created': 'Case note created',
  'case.anonymized': 'Case anonymised',
  'case.personal_data_erased': 'Case personal data erased',
  'case.imported': 'Case imported',
  'visit.scheduled': 'Visit scheduled',
  'visit.completed': 'Visit completed',
  'visit.rescheduled': 'Visit rescheduled',
  'visit.started': 'Visit started',
  'visit.note.merged': 'Visit note merged',
  'case.intervention.created': 'Intervention created',
  'case.intervention.updated': 'Intervention updated',
  'court.sitting.created': 'Court sitting created',
  'court.sitting.updated': 'Court sitting updated',
  'court.sitting.reminder_sent': 'Court reminder sent',
  'court.sitting.miss_escalated': 'Court miss escalated',
  'travel.claim.created': 'Travel claim created',
  'travel.claim.updated': 'Travel claim updated',
  'travel.claim.submitted': 'Travel claim submitted',
  'travel.claim.approved': 'Travel claim approved',
  'travel.claim.returned': 'Travel claim returned',
  'attachment.presign.issued': 'Upload URL issued',
  'attachment.confirmed': 'Attachment confirmed',
  'legend.created': 'Legend created',
  'legend.updated': 'Legend updated',
  'legend.deactivated': 'Legend deactivated',
  'legend.reactivated': 'Legend reactivated',
  'staff.created': 'Staff created',
  'staff.updated': 'Staff updated',
  'staff.deactivated': 'Staff deactivated',
  'staff.reactivated': 'Staff reactivated',
  'staff.force-reset': 'Staff force reset',
  'migration.validation_run': 'Migration validation run',
  'migration.import_completed': 'Migration import completed',
  'budget.created': 'Budget created',
  'budget.updated': 'Budget updated',
  'budget.proposed': 'Budget proposed',
  'budget.approved': 'Budget approved',
  'budget.returned': 'Budget returned',
  'budget.executed': 'Budget executed',
  'budget.utilization.created': 'Budget utilization created',
  'budget.utilization.updated': 'Budget utilization updated',
  'budget.utilization.deleted': 'Budget utilization deleted',
  'invitation.sent': 'Invitation Sent',
  'invitation.resent': 'Invitation Resent',
  'invitation.resent_notified': 'Inviter Notified of Resend',
  'user.suspended': 'User Suspended',
  'user.reactivated': 'User Reactivated',
  'user.deleted': 'User Deleted',
  'user.two_factor_provisioned': '2FA Provisioned',
  'user.two_factor_enrolled': '2FA Enrolled',
  'user.two_factor_reset': '2FA Reset',
  'activation_reissued': 'Activation Reissued',
  'organisation.activated': 'Organisation Activated',
};

export function formatEventType(eventType: string): string {
  return EVENT_TYPE_LABELS[eventType] ?? eventType;
}

export const EVENT_TYPE_OPTIONS = Object.keys(EVENT_TYPE_LABELS).sort();
